services:
  bot:
    container_name: uivk_bot
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    volumes:
      - ./src/database/database:/app/src/database/database
    depends_on:
      - redis
    restart: always

  redis:
    container_name: uivk_redis
    image: redis:7.4
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always

